local map = require("core.map")

local function diagnostic_jump(count)
  vim.diagnostic.jump({ count = count, float = true })
end

map.set("n", "<Esc>", "<cmd>nohlsearch<cr>", "Clear search highlight")
map.set("n", "Q", "<nop>", "Disable Ex mode")

map.set("v", ">", ">gv", "Indent right")
map.set("v", "<", "<gv", "Indent left")

map.set("n", "Y", "yy", "Yank line")
map.set({ "n", "x" }, "<leader>y", '"+y', "Yank to system clipboard")
map.set("n", "<leader>Y", '"+Y', "Yank line to system clipboard")
map.set("x", "<leader>p", '"_dP', "Paste without replacing yank")
map.set("x", "<C-c>", '"+y', "Copy selection to clipboard")
map.set("n", "<C-c>", function()
  vim.fn.setreg("+", vim.fn.getline("."))
end, "Copy line to clipboard")

map.set("n", "[q", "<cmd>cprev<cr>", "Previous quickfix item")
map.set("n", "]q", "<cmd>cnext<cr>", "Next quickfix item")
map.set("n", "<leader>xo", "<cmd>copen<cr>", "Open quickfix list")
map.set("n", "<leader>xq", "<cmd>cclose<cr>", "Close quickfix list")
map.set("n", "<leader>xn", "<cmd>cnext<cr>", "Next quickfix item")
map.set("n", "<leader>xp", "<cmd>cprev<cr>", "Previous quickfix item")
map.set("n", "<leader>xl", "<cmd>lopen<cr>", "Open location list")
map.set("n", "<leader>xL", "<cmd>lclose<cr>", "Close location list")

map.set("n", "[d", function()
  diagnostic_jump(-1)
end, "Previous diagnostic")
map.set("n", "]d", function()
  diagnostic_jump(1)
end, "Next diagnostic")
map.set("n", "<leader>ge", function()
  diagnostic_jump(1)
end, "Next diagnostic")
map.set("n", "<leader>gE", function()
  diagnostic_jump(-1)
end, "Previous diagnostic")
map.set("n", "<leader>xd", vim.diagnostic.setloclist, "Diagnostics to location list")
map.set("n", "<leader>xx", vim.diagnostic.setloclist, "Diagnostics to location list")

map.set("n", "<C-h>", "<C-w>h", "Window left")
map.set("n", "<C-j>", "<C-w>j", "Window down")
map.set("n", "<C-k>", "<C-w>k", "Window up")
map.set("n", "<C-l>", "<C-w>l", "Window right")
map.set("n", "<leader>ws", "<cmd>split<cr>", "Split below")
map.set("n", "<leader>wv", "<cmd>vsplit<cr>", "Split right")
map.set("n", "<leader>wd", "<cmd>close<cr>", "Close window")
map.set("n", "<leader>wo", "<cmd>only<cr>", "Keep only this window")
map.set("n", "<leader>w=", "<C-w>=", "Balance windows")
map.set("n", "<leader>wH", "<C-w>H", "Move window far left")
map.set("n", "<leader>wL", "<C-w>L", "Move window far right")

map.set("n", "gt", "<cmd>bnext<cr>", "Next buffer")
map.set("n", "gT", "<cmd>bprevious<cr>", "Previous buffer")
map.set("n", "]b", "<cmd>bnext<cr>", "Next buffer")
map.set("n", "[b", "<cmd>bprevious<cr>", "Previous buffer")
map.set("n", "<leader>bn", "<cmd>bnext<cr>", "Next buffer")
map.set("n", "<leader>bp", "<cmd>bprevious<cr>", "Previous buffer")

map.set("t", "<Esc><Esc>", "<C-\\><C-n>", "Terminal normal mode")
map.set("t", "<C-h>", "<C-\\><C-n><C-w>h", "Terminal window left")
map.set("t", "<C-j>", "<C-\\><C-n><C-w>j", "Terminal window down")
map.set("t", "<C-k>", "<C-\\><C-n><C-w>k", "Terminal window up")
map.set("t", "<C-l>", "<C-\\><C-n><C-w>l", "Terminal window right")
