{
  pkgs,
  coomerPkg,
  drcomClientPkg,
  ani2xcursorPkg,
  noctaliaPkg,
  ...
}:

{
  programs.steam.enable = true;
  programs.direnv.enable = true;
  environment.systemPackages =
    with pkgs;
    [
      alsa-firmware
      alsa-ucm-conf
      adw-gtk3
      bibata-cursors
      bluetui
      bluez
      btop
      brightnessctl
      btrfs-progs
      cava
      cliphist
      cmatrix
      codex
      csvlens
      curl
      cmake
      ddcutil
      delta
      duf
      dust
      dconf
      emacs-pgtk
      emacsPackages.vterm
      efibootmgr
      eza
      exfatprogs
      fastfetch
      fd
      fzf
      feh
      ffmpeg
      fuzzel
      gamescope
      git
      glib
      gparted
      google-chrome
      gpu-screen-recorder
      inetutils
      gnumake
      nodejs
      nh
      nixd
      nix-tree
      nixfmt
      nvtopPackages.full
      jq
      kitty
      lutris
      libreoffice-fresh
      mangohud
      mpv
      neovim
      nyancat
      openssh
      libnotify
      nwg-look
      networkmanagerapplet
      (obs-studio.override { browserSupport = false; })
      parted
      pavucontrol
      pciutils
      playerctl
      qq
      ripgrep
      satty
      splayer
      starship
      sunshine
      shellcheck
      tela-circle-icon-theme
      tree
      typora
      unzip
      vim
      vscode
      wechat
      wev
      wget
      wl-clipboard
      wl-clip-persist
      xwayland-satellite
      yazi
      zathura
      zathuraPkgs.zathura_pdf_poppler
      zoxide
      zip
      coomerPkg
      drcomClientPkg
      ani2xcursorPkg
      noctaliaPkg
    ]
    ++ (with pkgs.kdePackages; [
      qt6ct
    ]);
}
