require("core.options")
require("core.keymaps")
require("core.autocmds")
require("core.compat").setup()
require("core.packages").setup()

require("modules.ui").setup()
require("modules.completion").setup()
require("modules.lsp").setup()
require("modules.programming").setup()
require("modules.tools").setup()
require("modules.navigation").setup()
require("modules.ai").setup()
require("modules.functions").setup()
