mixed-port: 8907
mode: rule

external-controller: 127.0.0.1:9090
secret: "123456"

allow-lan: true
bind-address: 0.0.0.0

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  ipv6-timeout: 300
  respect-rules: false
  enhanced-mode: fake-ip
  use-hosts: false
  use-system-hosts: false
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*"
    - +.lan
    - +.local
    - time.*.com
    - ntp.*.com
    - +.market.xiaomi.com
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - +.qq.com
    - +.tencent.com
    - +.msftconnecttest.com
    - +.msftncsi.com
  default-nameserver:
    - tls://223.5.5.5
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  proxy-server-nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  direct-nameserver: []
  nameserver-policy: {}

tun:
  enable: true
  device: Meta
  stack: gvisor
  auto-route: true
  auto-redirect: false
  auto-detect-interface: true
  dns-hijack:
    - any:53
  route-exclude-address: []
  mtu: 1500

proxy-providers:
  prov_lmy:
    type: http
    url: "https://d3ism8qdnfdr0l.cloudfront.net/api/v1/client/subscribe?token=66aed7b607ac846cab915f267d0de94d"
    interval: 3600
    path: ./proxies/老猫云.yaml
  prov_yzhx:
    type: http
    url: "https://kaimenlai.com/clashx/00174382-7a33-4afa-97cc-8aa34c5720ce"
    interval: 3600
    path: ./proxies/一枝红杏.yaml

proxy-groups:
  - name: AUTO_一枝红杏
    type: fallback
    use: [prov_yzhx]
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50

  - name: 一枝红杏
    type: select
    use: [prov_yzhx]

  - name: AUTO_老猫云
    type: fallback
    use: [prov_lmy]
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50

  - name: 老猫云
    type: select
    use: [prov_lmy]

  - name: PROXY
    type: select
    proxies:
      - AUTO_一枝红杏
      - 一枝红杏
      - AUTO_老猫云
      - 老猫云
      - DIRECT

  - name: GLOBAL
    type: select
    proxies:
      - PROXY
      - DIRECT

rule-providers:
  Reject_ip:
    type: http
    interval: 1800
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/REJECT/ip/Reject_ip.yaml
    path: ./rules/REJECT/ip/Reject_ip.yaml
  Reject_no_ip:
    type: http
    interval: 1800
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/REJECT/no_ip/Reject_no_ip.yaml
    path: ./rules/REJECT/no_ip/Reject_no_ip.yaml
  Reject_domainset:
    type: http
    interval: 1800
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/REJECT/no_ip/Reject_domainset.yaml
    path: ./rules/REJECT/no_ip/Reject_domainset.yaml
  Reject_no_ip_drop:
    type: http
    interval: 1800
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/REJECT/no_ip/Reject_no_ip_drop.yaml
    path: ./rules/REJECT/no_ip/Reject_no_ip_drop.yaml
  Reject_no_ip_no_drop:
    type: http
    interval: 1800
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/REJECT/no_ip/Reject_no_ip_no_drop.yaml
    path: ./rules/REJECT/no_ip/Reject_no_ip_no_drop.yaml
  China_ip:
    type: http
    interval: 1800
    behavior: ipcidr
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/DIRECT/ip/China_ip.yaml
    path: ./rules/DIRECT/ip/China_ip.yaml
  Domestic_ip:
    type: http
    interval: 1800
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/DIRECT/ip/Domestic_ip.yaml
    path: ./rules/DIRECT/ip/Domestic_ip.yaml
  GoogleFCM_ip:
    type: http
    interval: 1800
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/DIRECT/ip/GoogleFCM_ip.yaml
    path: ./rules/DIRECT/ip/GoogleFCM_ip.yaml
  Lan_ip:
    type: http
    interval: 1800
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/DIRECT/ip/Lan_ip.yaml
    path: ./rules/DIRECT/ip/Lan_ip.yaml
  NetEaseMusic_ip:
    type: http
    interval: 1800
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/DIRECT/ip/NetEaseMusic_ip.yaml
    path: ./rules/DIRECT/ip/NetEaseMusic_ip.yaml
  SteamCN_ip:
    type: http
    interval: 1800
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/DIRECT/ip/SteamCN_ip.yaml
    path: ./rules/DIRECT/ip/SteamCN_ip.yaml
  AppleCDN_no_ip:
    type: http
    interval: 1800
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/DIRECT/no_ip/AppleCDN_no_ip.yaml
    path: ./rules/DIRECT/no_ip/AppleCDN_no_ip.yaml
  AppleCN_no_ip:
    type: http
    interval: 1800
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/DIRECT/no_ip/AppleCN_no_ip.yaml
    path: ./rules/DIRECT/no_ip/AppleCN_no_ip.yaml
  Direct_no_ip:
    type: http
    interval: 1800
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/DIRECT/no_ip/Direct_no_ip.yaml
    path: ./rules/DIRECT/no_ip/Direct_no_ip.yaml
  Domestic_no_ip:
    type: http
    interval: 1800
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/DIRECT/no_ip/Domestic_no_ip.yaml
    path: ./rules/DIRECT/no_ip/Domestic_no_ip.yaml
  GoogleFCM_no_ip:
    type: http
    interval: 1800
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/DIRECT/no_ip/GoogleFCM_no_ip.yaml
    path: ./rules/DIRECT/no_ip/GoogleFCM_no_ip.yaml
  Lan_no_ip:
    type: http
    interval: 1800
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/DIRECT/no_ip/Lan_no_ip.yaml
    path: ./rules/DIRECT/no_ip/Lan_no_ip.yaml
  MicrosoftCDN_no_ip:
    type: http
    interval: 1800
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/DIRECT/no_ip/MicrosoftCDN_no_ip.yaml
    path: ./rules/DIRECT/no_ip/MicrosoftCDN_no_ip.yaml
  NetEaseMusic_no_ip:
    type: http
    interval: 1800
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/DIRECT/no_ip/NetEaseMusic_no_ip.yaml
    path: ./rules/DIRECT/no_ip/NetEaseMusic_no_ip.yaml
  SteamCN_no_ip:
    type: http
    interval: 1800
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/DIRECT/no_ip/SteamCN_no_ip.yaml
    path: ./rules/DIRECT/no_ip/SteamCN_no_ip.yaml
  SteamRegion_no_ip:
    type: http
    interval: 1800
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/DIRECT/no_ip/SteamRegion_no_ip.yaml
    path: ./rules/DIRECT/no_ip/SteamRegion_no_ip.yaml
  Stream_ip:
    type: http
    interval: 1800
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/PROXY/ip/Stream_ip.yaml
    path: ./rules/PROXY/ip/Stream_ip.yaml
  Telegram_ip:
    type: http
    interval: 1800
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/PROXY/ip/Telegram_ip.yaml
    path: ./rules/PROXY/ip/Telegram_ip.yaml
  AI_no_ip:
    type: http
    interval: 1800
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/PROXY/no_ip/AI_no_ip.yaml
    path: ./rules/PROXY/no_ip/AI_no_ip.yaml
  Apple_no_ip:
    type: http
    interval: 1800
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/PROXY/no_ip/Apple_no_ip.yaml
    path: ./rules/PROXY/no_ip/Apple_no_ip.yaml
  CDN_domainset:
    type: http
    interval: 1800
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/PROXY/no_ip/CDN_domainset.yaml
    path: ./rules/PROXY/no_ip/CDN_domainset.yaml
  CDN_no_ip:
    type: http
    interval: 1800
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/PROXY/no_ip/CDN_no_ip.yaml
    path: ./rules/PROXY/no_ip/CDN_no_ip.yaml
  CustomProxy_no_ip:
    type: http
    interval: 1800
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/PROXY/no_ip/CustomProxy_no_ip.yaml
    path: ./rules/PROXY/no_ip/CustomProxy_no_ip.yaml
  Download_domainset:
    type: http
    interval: 1800
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/PROXY/no_ip/Download_domainset.yaml
    path: ./rules/PROXY/no_ip/Download_domainset.yaml
  Download_no_ip:
    type: http
    interval: 1800
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/PROXY/no_ip/Download_no_ip.yaml
    path: ./rules/PROXY/no_ip/Download_no_ip.yaml
  Global_no_ip:
    type: http
    interval: 1800
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/PROXY/no_ip/Global_no_ip.yaml
    path: ./rules/PROXY/no_ip/Global_no_ip.yaml
  Microsoft_no_ip:
    type: http
    interval: 1800
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/PROXY/no_ip/Microsoft_no_ip.yaml
    path: ./rules/PROXY/no_ip/Microsoft_no_ip.yaml
  Steam_no_ip:
    type: http
    interval: 1800
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/PROXY/no_ip/Steam_no_ip.yaml
    path: ./rules/PROXY/no_ip/Steam_no_ip.yaml
  Stream_no_ip:
    type: http
    interval: 1800
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/PROXY/no_ip/Stream_no_ip.yaml
    path: ./rules/PROXY/no_ip/Stream_no_ip.yaml
  Emby_no_ip:
    type: http
    interval: 1800
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/PROXY/no_ip/Emby_no_ip.yaml
    path: ./rules/PROXY/no_ip/Emby_no_ip.yaml
  Telegram_no_ip:
    type: http
    interval: 1800
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/RealSeek/Clash_Rule_DIY/refs/heads/mihomo/PROXY/no_ip/Telegram_no_ip.yaml
    path: ./rules/PROXY/no_ip/Telegram_no_ip.yaml

rules:
  - RULE-SET,Reject_no_ip,REJECT
  - RULE-SET,Reject_domainset,REJECT
  - RULE-SET,Reject_no_ip_drop,REJECT-DROP
  - RULE-SET,Reject_no_ip_no_drop,REJECT
  - RULE-SET,Reject_ip,REJECT

  - RULE-SET,CustomProxy_no_ip,PROXY
  - RULE-SET,AI_no_ip,PROXY
  - RULE-SET,Global_no_ip,PROXY
  - RULE-SET,Download_domainset,PROXY
  - RULE-SET,Download_no_ip,PROXY
  - RULE-SET,Stream_no_ip,PROXY
  - RULE-SET,Stream_ip,PROXY
  - RULE-SET,Telegram_no_ip,PROXY
  - RULE-SET,Telegram_ip,PROXY
  - RULE-SET,Steam_no_ip,PROXY
  - RULE-SET,Emby_no_ip,PROXY
  - RULE-SET,CDN_domainset,PROXY
  - RULE-SET,CDN_no_ip,PROXY
  - RULE-SET,Apple_no_ip,PROXY
  - RULE-SET,Microsoft_no_ip,PROXY

  - RULE-SET,Lan_no_ip,DIRECT
  - RULE-SET,Lan_ip,DIRECT
  - RULE-SET,Domestic_no_ip,DIRECT
  - RULE-SET,Domestic_ip,DIRECT
  - RULE-SET,Direct_no_ip,DIRECT
  - RULE-SET,China_ip,DIRECT

  - RULE-SET,NetEaseMusic_no_ip,DIRECT
  - RULE-SET,NetEaseMusic_ip,DIRECT
  - RULE-SET,SteamCN_no_ip,DIRECT
  - RULE-SET,SteamCN_ip,DIRECT
  - RULE-SET,SteamRegion_no_ip,DIRECT

  - RULE-SET,AppleCDN_no_ip,DIRECT
  - RULE-SET,AppleCN_no_ip,DIRECT
  - RULE-SET,MicrosoftCDN_no_ip,DIRECT
  - RULE-SET,GoogleFCM_no_ip,DIRECT
  - RULE-SET,GoogleFCM_ip,DIRECT

  - MATCH,PROXY
