font_family Maple Mono NF CN
font_size 12.0

background_opacity 0.93
confirm_os_window_close 0
cursor_trail 0
pixel_scroll yes
scrollback_lines 1000
wheel_scroll_min_lines 1
enable_audio_bell no
window_padding_width 4
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
enabled_layouts  tall,stack

# keybinds
map ctrl+c copy_or_interrupt
map ctrl+v paste_from_clipboard
map ctrl+shift+enter new_window_with_cwd
